#!/bin/sh
set -eu

CONFIG_FILE="/config/config.yaml"
PROVIDERS_DIR="/config/providers"
HEALTHCHECK_URL="https://www.gstatic.com/generate_204"

mkdir -p "$PROVIDERS_DIR"

cat > "$CONFIG_FILE" <<EOF
# This file is autogenerated by render-config.sh.

mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: true

external-controller: 0.0.0.0:9090
external-controller-cors:
  allow-origins:
    - "*"
  allow-private-network: true
secret: ""

profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  direct-nameserver:
    - system

proxies:
  - name: MOCK
    type: http
    server: 127.0.0.1
    port: 65535
EOF

PROVIDERS=""

write_provider_block() {
  index="$1"
  url="$2"
  provider="sub${index}"

  cat >> "$CONFIG_FILE" <<EOF
  ${provider}:
    type: http
    url: "${url}"
    path: ./providers/${provider}.yaml
    interval: 3600
    proxy: DIRECT
    health-check:
      enable: true
      url: ${HEALTHCHECK_URL}
      interval: 600
EOF
}

write_region_group() {
  name="$1"
  filter="$2"

  cat >> "$CONFIG_FILE" <<EOF

  - name: ${name}
    type: url-test
    url: ${HEALTHCHECK_URL}
    interval: 300
    tolerance: 50
    use:
EOF

  for provider in $PROVIDERS; do
    printf '      - %s\n' "$provider" >> "$CONFIG_FILE"
  done

  cat >> "$CONFIG_FILE" <<EOF
    filter: "${filter}"
EOF
}

if [ -n "${SUBSCRIPTION_1_URL:-}" ] || [ -n "${SUBSCRIPTION_2_URL:-}" ] || [ -n "${SUBSCRIPTION_3_URL:-}" ]; then
  cat >> "$CONFIG_FILE" <<EOF

proxy-providers:
EOF

  if [ -n "${SUBSCRIPTION_1_URL:-}" ]; then
    write_provider_block 1 "$SUBSCRIPTION_1_URL"
    PROVIDERS="$PROVIDERS sub1"
  fi

  if [ -n "${SUBSCRIPTION_2_URL:-}" ]; then
    write_provider_block 2 "$SUBSCRIPTION_2_URL"
    PROVIDERS="$PROVIDERS sub2"
  fi

  if [ -n "${SUBSCRIPTION_3_URL:-}" ]; then
    write_provider_block 3 "$SUBSCRIPTION_3_URL"
    PROVIDERS="$PROVIDERS sub3"
  fi

  cat >> "$CONFIG_FILE" <<EOF

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - AUTO
      - FALLBACK
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - MOCK
      - DIRECT
    use:
EOF

  for provider in $PROVIDERS; do
    printf '      - %s\n' "$provider" >> "$CONFIG_FILE"
  done

  cat >> "$CONFIG_FILE" <<EOF

  - name: AUTO
    type: url-test
    url: ${HEALTHCHECK_URL}
    interval: 300
    tolerance: 50
    use:
EOF

  for provider in $PROVIDERS; do
    printf '      - %s\n' "$provider" >> "$CONFIG_FILE"
  done

  cat >> "$CONFIG_FILE" <<EOF

  - name: FALLBACK
    type: fallback
    url: ${HEALTHCHECK_URL}
    interval: 300
    use:
EOF

  for provider in $PROVIDERS; do
    printf '      - %s\n' "$provider" >> "$CONFIG_FILE"
  done

  write_region_group "香港" "香港|HK|Hong Kong|🇭🇰"
  write_region_group "台湾" "台湾|台灣|TW|Taiwan|🇹🇼"
  write_region_group "日本" "日本|JP|Japan|东京|大阪|🇯🇵"
  write_region_group "新加坡" "新加坡|SG|Singapore|狮城|🇸🇬"
  write_region_group "美国" "美国|US|USA|United States|美[国國]|洛杉矶|硅谷|西雅图|纽约|🇺🇸"
else
  cat >> "$CONFIG_FILE" <<EOF

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - MOCK
      - DIRECT
EOF
fi

cat >> "$CONFIG_FILE" <<EOF

rules:
  - MATCH,PROXY
EOF

exec /mihomo -d /config -f "$CONFIG_FILE" -secret "${MIHOMO_SECRET:-}"